import Head from 'next/head';
import Header from '../components/Header.js';

import { useContext } from 'react';
import { ThemeContext } from '../contexts/theme';
import About from '../components/About.js';
import Projects from '../components/Projects.js';
import Skills from '../components/Skills.js';
import Contact from '../components/Contact.js';
import Footer from '../components/Footer.js';
import ScrollToTop from '../components/ScrollToTop.js';

export default function Home() {
  const [{ themeName }] = useContext(ThemeContext);
  return (
    <>
      <Head>
        <title>Tue An</title>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap'
          rel='stylesheet'
        />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <div id='top' className={`${themeName} app`}>
        <Header />
        <main>
          <About />
          <Projects />
          <Skills />
          <Contact />
        </main>

        <ScrollToTop />
        <Footer />
      </div>
    </>
  );
}
